apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 22.7.1
    helm:
      values: |
        global:
          storageClass: "standard"
        
        airflow:
          auth:
            username: admin
            password: admin123
          configuration:
            core:
              load_examples: false
            webserver:
              expose_config: true
          
        executor: CeleryExecutor
        
        postgresql:
          enabled: true
          auth:
            username: airflow
            password: airflow123
            database: airflow
        
        redis:
          enabled: true
          auth:
            enabled: true
            password: redis123
        
        workers:
          replicas: 2
        
        web:
          service:
            type: ClusterIP
            ports:
              http: 8080
        
        dags:
          persistence:
            enabled: true
            size: 1Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
