## Bitnami Airflow values configuration
executor: local

airflow:
  image:
    registry: docker.io
    repository: apache/airflow
    tag: 2.9.1
    pullPolicy: IfNotPresent
  
  configurationConfigMap: ~
  
  extraEnvVars:
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "false"
    - name: AIRFLOW__API__AUTH_BACKENDS
      value: "airflow.api.auth.backend.basic_auth"
  
  auth:
    username: admin
    password: admin
    email: admin@example.com
    firstname: Admin
    lastname: User
    
  web:
    service:
      type: LoadBalancer
      port: 8080

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: false

dags:
  persistence:
    enabled: true
  gitSync:
    enabled: false
    
ingress:
  enabled: false
